config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "tweets#index"
  resources :tweets
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :img, ImgUploader
  has_many_attached :imgs
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tweets
  
  def full_profile?
    image.attached?  && store_name?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:store_name])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.page(params[:page]).per(3).order('updated_at DESC')
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    Tweet.create(img: tweet_params[:img], text: tweet_params[:text], user_id: current_user.id)
  end
  
  def update
    current_user.update(tweet_params)
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:img, :text, :img_cache, :remove_img)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end
  
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order("created_at DESC").page(params[:page]).per(3)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    current_user.update(update_params)
  end
  
  private
  def update_params
    params.require(:user).permit(:store_name, :zip_cord, :loc, :phone, :email, :hp_url, :remarks, :delivery, :take_out, :start_time, :end_time, :mon_hol,:tue_hol, :wed_hol, :thu_hol, :fri_hol, :sat_hol, :sun_hol, :hol_hol, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nojisyuku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/index.html.erb
<p>自粛じゃ死ぬ！なんとか助けて下さい！！</p>
<% if user_signed_in? && current_user.full_profile? %>
    <a href="tweets/new">投稿する</a>
    <%= link_to '登録情報', "/users/#{current_user.id}", method: :get %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
  <% unless user_signed_in? %>
    <%= link_to "ログイン", new_user_session_path, class: 'post' %>
    <%= link_to "店舗登録はこちら", new_user_registration_path, class: 'post' %>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <% unless current_user.full_profile? %>
    <header class="header_top panel panel-default col-lg-12 no-profile">
      <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
      <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </header>
    <% end %>
<% end %>



<% @tweets.each do |tweet| %>

  <ul>
    <li>店名：<%= tweet.user.store_name %></li>
    <li><%= image_tag tweet.img.to_s %></li>
    <li><%= tweet.text %></li>
  </ul>
<% end %>


    

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">

    <h3>
      投稿する
    </h3>
    <%= form_with(model: @tweet, local: true) do |form| %>
    <%= form.label :text %>
    <%= form.text_field :text %>
    <div class="form-group file">
      <%= form.file_field :img, id: :tweet_img %>
      <p><%= form.check_box :remove_img %>画像を削除する</p>
      </div>
      <div class="form-group">
        <%= form.submit "送信", class: "btn btn-primary withripple" %>
      </div>
<% end %>
  </div>
</div>

app/views/users/edit.html.erb
  <%= link_to '登録情報', "/users/#{current_user.id}", method: :get %>
  <div class="contents">
    <div class="text text01">
      <%= form_with(model: @user, url: {controller: 'users', action: 'update' }, local: true) do |form| %>
      <h2>登録情報</h2>
      <div class="col-lg-6">
        <%= form.label :store_name, "店名" %>
        <%= form.text_field :store_name, placeholder: "店名", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :zip_cord, "郵便番号" %>
        <%= form.text_field :zip_cord, placeholder: "郵便番号", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :loc, "所在地" %>
        <%= form.text_field :loc, placeholder: "所在地", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :phone, "電話番号" %>
        <%= form.text_field :phone, placeholder: "電話番号", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :email, "メールアドレス" %>
        <%= form.email_field :email, placeholder: "メールアドレス", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :hp_url, "ホームページ" %>
        <%= form.text_field :hp_url, placeholder: "ホームページ", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :delivery, "出前" %>
        <%= form.select :delivery, [ ["可能"], ["不可"], ["要相談"] ], prompt: "選択してください" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :take_out, "持ち帰り" %>
        <%= form.select :take_out, [ ["可能"], ["不可"], ["要相談"] ], prompt: "選択してください" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :start_time, "営業開始時間" %>
        <%= form.time_select :start_time, placeholder: "営業開始時間", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :end_time, "終業時間" %>
        <%= form.time_select :end_time, placeholder: "終業時間", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :pre_time, "準備・休憩時間等ありましたらお書き下さい。" %>
        <%= form.text_field :pre_start, placeholder: "13:00〜17:00など", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= form.label :remarks, "備考" %>
        <%= form.text_field :remarks, placeholder: "備考", class: "form-control" %>
      </div>
      <div class="field">
        定休日にチェックを入れて下さい。
        <ul>
          <li>
            <%= form.label :mon_hol, "月曜日" %>
            <%= form.radio_button :mon_hol, "営業日" %> 営業日 <%= form.radio_button :mon_hol, "休業日" %> 休業日 <%= form.radio_button :mon_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :tue_hol, "火曜日" %>
            <%= form.radio_button :tue_hol, "営業日" %> 営業日 <%= form.radio_button :tue_hol, "休業日" %> 休業日 <%= form.radio_button :tue_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :wed_hol, "水曜日" %>
            <%= form.radio_button :wed_hol, "営業日" %> 営業日 <%= form.radio_button :wed_hol, "休業日" %> 休業日 <%= form.radio_button :wed_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :thu_hol, "木曜日" %>
            <%= form.radio_button :thu_hol, "営業日" %> 営業日 <%= form.radio_button :thu_hol, "休業日" %> 休業日 <%= form.radio_button :thu_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :fri_hol, "金曜日" %>
            <%= form.radio_button :fri_hol, "営業日" %> 営業日 <%= form.radio_button :fri_hol, "休業日" %> 休業日 <%= form.radio_button :fri_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :sat_hol, "土曜日" %>
            <%= form.radio_button :sat_hol, "営業日" %> 営業日 <%= form.radio_button :sat_hol, "休業日" %> 休業日 <%= form.radio_button :sat_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :sun_hol, "日曜日" %>
            <%= form.radio_button :sun_hol, "営業日" %> 営業日 <%= form.radio_button :sun_hol, "休業日" %> 休業日 <%= form.radio_button :sun_hol, "不定休" %> 不定休
          </li>
          <li>
            <%= form.label :hol_hol, "祝　日" %>
            <%= form.radio_button :hol_hol, "営業日" %> 営業日 <%= form.radio_button :hol_hol, "休業日" %> 休業日 <%= form.radio_button :hol_hol, "不定休" %> 不定休
          </li>
        </ul>
      </div>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
      <% if @user.image.attached? %>
        <div class="image" style="background-image: url(<%= rails_blob_path(@user.image) %>)"></div>
      <% else %>
        <div class="image"><%= image_tag "default_user.png" %></div>
      <% end %>
        <%= form.file_field :image, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <div class="form-group">
        <%= form.submit "送信", class: "btn btn-primary withripple" %>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% unless current_user.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
    <p>Profyは友達の質問に答えながらプロフィールを作るサービスです！</p>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
  </header>
<% else %>

<% end %>

app/views/users/show.html.erb
<div class="contents row">
  <a href="/tweets/new">近況を投稿をする</a>
  <p><%= @user.store_name %>さんの登録状況</p>
  <% if @user.image.attached? %>
  <div class="image" style="background-image: url(<%= rails_blob_path(@user.image) %>)"></div>
  <% else %>
  <div class="image"><%= image_tag "default_user.png" %></div>
  <% end %>
  
  <ul>
    <li>所在地：<%= @user.zip_cord %> <%= @user.loc %></li>
    <li>TEL番号：<%= @user.phone %></li>
    <li>メール：<%= @user.email %></li>
    <li>ホームページ：<%= @user.hp_url %></li>
    <li>出前：<%= @user.delivery %></li>
    <li>持ち帰り：<%= @user.take_out %></li>
  </ul>
  <ul>営業日
    <li>月曜日：<%= @user.mon_hol %></li>
    <li>火曜日：<%= @user.tue_hol %></li>
    <li>水曜日：<%= @user.tue_hol %></li>
    <li>木曜日：<%= @user.wed_hol %></li>
    <li>金曜日：<%= @user.thu_hol %></li>
    <li>土曜日：<%= @user.sat_hol %></li>
    <li>日曜日：<%= @user.sun_hol %></li>
    <li>祝　日：<%= @user.hol_hol %></li>
    <li>備考<%= @user.remarks %></li>
  </ul>
  
  <ul>
    <li>営業時間：<%= @user.start_time %> 〜 <%= @user.end_time %></li>
    <% unless @user.pre_time == "-" %>
    <li>準備時間：<%= @user.pre_time %></li>
    <% end %>

  </ul>
  <%= link_to "登録情報の変更はこちら", "/users/#{current_user.id}/edit", method: :get %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

  <p><%= @user.store_name %>さんの投稿</p>
  <% @tweets.each do |tweet| %>
    <ul>
    <li><%= tweet.user.store_name %></li>
    <li><%= image_tag tweet.img.to_s %></li>
    <li><%= tweet.text %></li>
  </ul>
  <% end %>

  
  <%= paginate(@tweets) %>
</div>

app/views/users/update.html.erb
更新しました
<%= link_to '登録情報に戻る', "/users/#{current_user.id}", method: :get %>